### ISSUE TITLE
[NativeScript/nativescript-ui-charts] [IOS] [NS 8.5.3] Command xcodebuild failed with exit code 65

### ISSUE THREAD

**Issue by vicmasa** [NativeScript/plugins#483]
Hi.

We use a lot of graphics in the apps, but they stopped working on IOS with the new version of Nativescript 8.5.3. We wrote [here](https://github.com/NativeScript/nativescript-ui-charts/issues/48) to the plugin creators repository [NativeScript/nativescript-ui-charts], but no responses. We would like to know what alternatives we have to be able to use graphics in Nativescript.

Thanks.

### Which platform(s) does your issue occur on?
- iOS
- iOS 16.4 
- emulator

```yaml
OS: macOS 13.3.1
CPU: (8) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 19.8.1
npm: 9.5.1
nativescript: 8.5.3

# android
java: 11.0.17
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.3/14E222b
cocoapods: 1.12.1
python: 2.7.18
python3: 3.9.6
ruby: 2.7.8
platforms: 
  - DriverKit 22.4
  - iOS 16.4
  - macOS 13.3
  - tvOS 16.4
  - watchOS 9.4
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "~8.5.0",
  "@nativescript/theme": "~3.0.2",
  "@nativescript/ui-charts": "^0.2.4"
},
"devDependencies": {
  "@nativescript/android": "8.5.0",
  "@nativescript/ios": "8.5.1",
  "@nativescript/webpack": "~5.0.14"
}
```
