### ISSUE TITLE
[nativescript-videoplayer][@nstudio/nativescript-exoplayer][ios] Streaming video does not play on ios

### ISSUE THREAD

**Issue by vicmasa** [NativeScript/plugins#494]
Hi everyone.
 
When I put the streaming URL, it does not play for IOS, but it plays on Android. I have tried with both videoplayer and exoplayer plugins, but I can't get it to play for IOS.

Github: https://github.com/vicmasa/ns853
URL Streaming: https://liveams.viiamanager.com:5443/LiveApp/streams/Invian-cid1-Jumbo_Screen_TEST-lid85-Flujo.m3u8 

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="loaded"
    xmlns:VideoPlayer="nativescript-videoplayer" xmlns:exoplayer="@nstudio/nativescript-exoplayer">
    <StackLayout>
        <VideoPlayer:Video width="300" height="280" controls="true" autoplay="true"
            src="https://liveams.viiamanager.com:5443/LiveApp/streams/Invian-cid1-Jumbo_Screen_TEST-lid85-Flujo.m3u8" />
        <exoplayer:Video width="300" height="280" autoplay="true"
            src="https://liveams.viiamanager.com:5443/LiveApp/streams/Invian-cid1-Jumbo_Screen_TEST-lid85-Flujo.m3u8" />
    </StackLayout>
</Page>

```
```yaml
OS: macOS 13.3.1
CPU: (8) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 19.8.1
npm: 9.5.1
nativescript: 8.5.3

# android
java: 11.0.17
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.3/14E222b
cocoapods: 1.12.1
python: 2.7.18
python3: 3.9.6
ruby: 2.7.8
platforms: 
  - DriverKit 22.4
  - iOS 16.4
  - macOS 13.3
  - tvOS 16.4
  - watchOS 9.4
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "~8.5.0",
  "@nativescript/theme": "~3.0.2",
  "@nativescript/ui-charts": "^0.4.0",
  "@nstudio/nativescript-exoplayer": "^6.1.0",
  "nativescript-videoplayer": "^5.0.1"
},
"devDependencies": {
  "@nativescript/android": "8.5.0",
  "@nativescript/ios": "8.5.1",
  "@nativescript/webpack": "~5.0.14"
}
```

<img width="1512" alt="image" src="https://github.com/NativeScript/plugins/assets/34837622/88068821-cfff-4e2d-a31e-0e3e3cdf9124">
