### ISSUE TITLE
nativescript/ionic-portal crashes android app

### ISSUE THREAD

**Issue by FerhatKoca** [NativeScript/plugins#538]
Hello, i'm currently trying to implement the ionic-portal plugin.

It works on ios, but if i try to start a android app it crashes and i get a error message:

```
System.err: An uncaught Exception occurred on "main" thread.
  System.err: Unable to start activity ComponentInfo{com.myproject.app.saas/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
  System.err: ReferenceError: io is not defined
  System.err:
  System.err: StackTrace:
  System.err: register(file: src/webpack:/saas/node_modules/@nativescript/ionic-portals/index.android.js:5:0)
  System.err:   at (file: src/webpack:/saas/src/main.ts:21:4)
```

This is how i register my portal in the main.ts:

```
Application.on(Application.launchEvent, () => {
  IonicPortalManager.register(
    'key'
  );
});

```

**Comment by NathanWalker** [comment]
Thank you for the report. 
Could you try “rm -rf platforms” and then run android again?

**Comment by FerhatKoca** [comment]
Hey Nathan, thanks for the fast reply.

I already did that. Also with nodes. But it still wouldn't work. If i remove the code from main.ts than it builds the app. Very strange :D 


Here is the rest of the error message, if it somehow helps:

```
System.err: An uncaught Exception occurred on "main" thread.
  System.err: Unable to start activity ComponentInfo{com.myproject.app.saas/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
  System.err: ReferenceError: io is not defined
  System.err:
  System.err: StackTrace:
  System.err: register(file: src/webpack:/saas/node_modules/@nativescript/ionic-portals/index.android.js:5:0)
  System.err:   at (file: src/webpack:/saas/src/main.ts:20:4)
  System.err:   at invokeTask(file: src/webpack:/saas/node_modules/zone.js/fesm2015/zone.js:409:0)
  System.err:   at runTask(file: src/webpack:/saas/node_modules/zone.js/fesm2015/zone.js:178:0)
  System.err:   at invokeTask(file: src/webpack:/saas/node_modules/zone.js/fesm2015/zone.js:490:0)
  System.err:   at ZoneTask.invoke(file: src/webpack:/saas/node_modules/zone.js/fesm2015/zone.js:479:0)
  System.err:   at _handleEvent(file: src/webpack:/saas/node_modules/@nativescript/core/data/observable/index.js:306:40)
  System.err:   at notify(file: src/webpack:/saas/node_modules/@nativescript/core/data/observable/index.js:287:23)
  System.err:   at notifyLaunch(file: src/webpack:/saas/node_modules/@nativescript/core/application/application-common.js:194:13)
  System.err:   at createRootView(file: src/webpack:/saas/node_modules/@nativescript/core/application/application-common.js:202:32)
  System.err:   at setActivityContent(file: src/webpack:/saas/node_modules/@nativescript/core/ui/frame/index.android.js:1174:19)
  System.err:   at onCreate(file: src/webpack:/saas/node_modules/@nativescript/core/ui/frame/index.android.js:1003:13)
  System.err:   at onCreate(file: src/webpack:/saas/node_modules/@nativescript/core/ui/frame/activity.android.js:21:0)
  System.err:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
  System.err:   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
  System.err:   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
  System.err:   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
  System.err:   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
  System.err:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
  System.err:   at android.os.Handler.dispatchMessage(Handler.java:106)
  System.err:   at android.os.Looper.loopOnce(Looper.java:201)
  System.err:   at android.os.Looper.loop(Looper.java:288)
  System.err:   at android.app.ActivityThread.main(ActivityThread.java:7872)
  System.err:   at java.lang.reflect.Method.invoke(Native Method)
  System.err:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  System.err:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
  System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
  System.err: ReferenceError: io is not defined
  System.err:   at com.tns.Runtime.callJSMethodNative(Native Method)
  System.err:   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1301)
  System.err:   at com.tns.Runtime.callJSMethodImpl(Runtime.java:1187)
  System.err:   at com.tns.Runtime.callJSMethod(Runtime.java:1174)
  System.err:   at com.tns.Runtime.callJSMethod(Runtime.java:1152)
  System.err:   at com.tns.Runtime.callJSMethod(Runtime.java:1148)
  System.err:   at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:57)
  System.err:   at android.app.Activity.performCreate(Activity.java:8305)
  System.err:   at android.app.Activity.performCreate(Activity.java:8284)
  System.err:   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
  System.err:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
  System.err:   ... 12 more
```
