### ISSUE TITLE
@nativescript/background-http doesn't support sdk 34 

### ISSUE THREAD

**Issue by vpetyov** [NativeScript/plugins#541]
The error is [One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts]

**Comment by serhiynovos** [comment]
The same for me

**Comment by NathanWalker** [comment]
Note: New receiver needs to be linked up: https://stackoverflow.com/a/77276774/2192332

**Comment by micflan** [comment]
Any progress on this, or a work-around in the meantime? Thanks

**Comment by sublime392** [comment]
> Any progress on this, or a work-around in the meantime? Thanks

I just ran into this when I updated targetSdkVersion and compileSdkVersion to 34. Rolling it back to 33 let's the app run on Android 14

**Comment by triniwiz** [comment]
Please try out the latest version as it supports API 33+

**Comment by NathanWalker** [comment]
Specifically `6.0.1`, let us know if any further issue there or if need reopening.

**Comment by pap5508** [comment]
@NathanWalker : I am still facing the same error 6.0.1 version.

**Comment by highlandmegseegmiller** [comment]
@NathanWalker and @triniwiz I am also still experiencing this error message when targeting sdk 34 (which will be required by the Google Play Store at end of August 2024). I am on v 6.0.1. App compiles if I drop to targeting sdk 33.

**Comment by edusperoni** [comment]
Hello! Can you report the full StackTrace for this? Please also try upgrading to `@nativescript/core@8.0.1` as we just fixed an issue that would output this error message

**Comment by highlandmegseegmiller** [comment]
I'm running `@nativescript/core@8.7.2` and `@nativescript/background-http@6.0.1`

Here's the full StackTrace:
```
System.err: An uncaught Exception occurred on "main" thread.
  System.err: Unable to start activity ComponentInfo{org.nativescript.app/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
  System.err: Error: java.lang.SecurityException: org.nativescript.app: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
  System.err:
  System.err: StackTrace:
  System.err: callback(file: src/webpack:/MyHighland/node_modules/@nativescript/background-http/index.android.js:24:0)
  System.err:   at _handleEvent(file: src/webpack:/MyHighland/node_modules/@nativescript/core/data/observable/index.js:306:0)
  System.err:   at notify(file: src/webpack:/MyHighland/node_modules/@nativescript/core/data/observable/index.js:287:0)
  System.err:   at notifyLaunch(file: src/webpack:/MyHighland/node_modules/@nativescript/core/application/application-common.js:195:0)
  System.err:   at createRootView(file: src/webpack:/MyHighland/node_modules/@nativescript/core/application/application-common.js:203:0)
  System.err:   at setActivityContent(file: src/webpack:/MyHighland/node_modules/@nativescript/core/ui/frame/index.android.js:1175:30)
  System.err:   at onCreate(file: src/webpack:/MyHighland/node_modules/@nativescript/core/ui/frame/index.android.js:1004:0)
  System.err:   at onCreate(file: src/webpack:/MyHighland/node_modules/@nativescript/core/ui/frame/activity.android.js:21:0)
  System.err:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
  System.err:   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
  System.err:   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
  System.err:   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
  System.err:   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
  System.err:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
  System.err:   at android.os.Handler.dispatchMessage(Handler.java:106)
  System.err:   at android.os.Looper.loopOnce(Looper.java:205)
  System.err:   at android.os.Looper.loop(Looper.java:294)
  System.err:   at android.app.ActivityThread.main(ActivityThread.java:8177)
  System.err:   at java.lang.reflect.Method.invoke(Native Method)
  System.err:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
  System.err:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
  System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
  System.err: Error: java.lang.SecurityException: org.nativescript.app: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
  System.err:   at com.tns.Runtime.callJSMethodNative(Native Method)
  System.err:   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1301)
  System.err:   at com.tns.Runtime.callJSMethodImpl(Runtime.java:1187)
  System.err:   at com.tns.Runtime.callJSMethod(Runtime.java:1174)
  System.err:   at com.tns.Runtime.callJSMethod(Runtime.java:1152)
  System.err:   at com.tns.Runtime.callJSMethod(Runtime.java:1148)
  System.err:   at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:57)
  System.err:   at android.app.Activity.performCreate(Activity.java:8595)
  System.err:   at android.app.Activity.performCreate(Activity.java:8573)
  System.err:   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
  System.err:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
  System.err:   ... 12 more
  System.err: Caused by: java.lang.SecurityException: org.nativescript.app: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
  System.err:   at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
  System.err:   at android.os.Parcel.createException(Parcel.java:3041)
  System.err:   at android.os.Parcel.readException(Parcel.java:3024)
  System.err:   at android.os.Parcel.readException(Parcel.java:2966)
  System.err:   at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
  System.err:   at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
  System.err:   at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
  System.err:   at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
  System.err:   at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
  System.err:   at net.gotev.uploadservice.observer.request.BaseRequestObserver.register(BaseRequestObserver.kt:36)
  System.err:   at net.gotev.uploadservice.observer.request.GlobalRequestObserver.<init>(GlobalRequestObserver.kt:12)
  System.err:   at net.gotev.uploadservice.observer.request.GlobalRequestObserver.<init>(GlobalRequestObserver.kt:9)
  System.err:   at net.gotev.uploadservice.observer.request.GlobalRequestObserver.<init>(Unknown Source:6)
  System.err:   ... 23 more
  System.err: Caused by: android.os.RemoteException: Remote stack trace:
  System.err:   at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13927)
  System.err:   at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
  System.err:   at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
  System.err:   at android.os.Binder.execTransactInternal(Binder.java:1339)
  System.err:   at android.os.Binder.execTransact(Binder.java:1275)
```
